### ISSUE TITLE
NestJs rules quite similar to mines 🤔

### ISSUE THREAD

**Issue by AlbertoBasalo** [PatrickJS/awesome-cursorrules#1]
Hi, 
your nestjs rules:
https://raw.githubusercontent.com/PatrickJS/awesome-cursorrules/main/rules/typescript-nestjs-best-practices-cursorrules-promp/.cursorrules

are pretty similar to mine:
https://cursor.directory/nestjs-clean-typescript-cursor-rules

submitted 3 weeks ago:
https://github.com/pontusab/cursor.directory/pulls?q=is%3Apr+is%3Aclosed+author%3AAlbertoBasalo

How do you get it?

**Comment by PatrickJS** [comment]
it looks like someone created a fork of yours. in every directory there is credit in a readme if you check. you can add yours to the list. theres a few directories: cursor.directory, cursordirectory, cursorlist and probably more. feel free to make a PR 👍
