### ISSUE TITLE
Are there any .cursorrules for Flutter?

### ISSUE THREAD

**Issue by tks-00** [PatrickJS/awesome-cursorrules#8]
Nice to meet you.

I am an engineer using Flutter.
I have had swift and others, but as the title says, it would be helpful to have Flutter .cursorrules.

---

はじめまして。

私は Flutter を使っているエンジニアです。
swift などはありましたが、タイトル通り、Flutter の .cursorrules があると助かります。

**Comment by PatrickJS** [comment]
Please make a PR 🫡

**Comment by PatrickJS** [comment]
done https://github.com/PatrickJS/awesome-cursorrules/pull/9
